package crystal

import (
	"crypto/rand"
	"fmt"
	"os"
	"strings"
)

// GenPicoHeader XOR-encrypts a Crystal Palace PICO binary and writes a C header
// file containing the encrypted bytes and key as static C arrays.
//
// This is a Go port of gen_pico_header.py. A fresh 256-byte random key is
// generated on every call so each crystal-exec.x64.dll has a unique byte
// pattern — defeats static signature matching on the embedded PICO.
//
// The generated header defines:
//
//	crystalexec_pico[]         — XOR-encrypted PICO bytes
//	crystalexec_pico_len       — byte count
//	crystalexec_pico_key[]     — 256-byte XOR key
//	crystalexec_pico_key_len   — always 256
func GenPicoHeader(picoPath, headerPath string) error {
	raw, err := os.ReadFile(picoPath)
	if err != nil {
		return fmt.Errorf("reading PICO: %w", err)
	}

	key := make([]byte, 256)
	if _, err := rand.Read(key); err != nil {
		return fmt.Errorf("generating key: %w", err)
	}

	enc := make([]byte, len(raw))
	for i, b := range raw {
		enc[i] = b ^ key[i%len(key)]
	}

	var sb strings.Builder
	sb.WriteString("/* auto-generated by crystalkit — do not edit */\n\n")
	writeArray(&sb, "crystalexec_pico_key", key)
	fmt.Fprintf(&sb, "static const unsigned int crystalexec_pico_key_len = %d;\n\n", len(key))
	writeArray(&sb, "crystalexec_pico", enc)
	fmt.Fprintf(&sb, "static const unsigned int crystalexec_pico_len = %d;\n", len(enc))

	if err := os.WriteFile(headerPath, []byte(sb.String()), 0o644); err != nil {
		return fmt.Errorf("writing header: %w", err)
	}

	fmt.Printf("[+] %s: %d bytes encrypted, key_len=%d\n", headerPath, len(raw), len(key))
	return nil
}

func writeArray(sb *strings.Builder, name string, data []byte) {
	fmt.Fprintf(sb, "static const unsigned char %s[] = {\n", name)
	for i := 0; i < len(data); i += 16 {
		sb.WriteString("    ")
		end := i + 16
		if end > len(data) {
			end = len(data)
		}
		for _, b := range data[i:end] {
			fmt.Fprintf(sb, "0x%02x,", b)
		}
		sb.WriteString("\n")
	}
	sb.WriteString("};\n")
}
